title: "Global Politics and Ecnomics Research Center"
email: gpercenter@gmail.com
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Nimesh Babu Oli
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Nimesh Babu Oli
    display_name: Nimesh
    avatar: 'assets/images/sal.png'
    email: nimeshbabuoli@gmail.com
    web: https://nimeshbabuoli.com.np/
    twitter: https://twitter.com/nimeshbabuoli
    description: "Co-founder of Global Politics and Economics Research Center"
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/gpercenter/
  facebook: https://www.facebook.com/gpercenter
  twitter: https://twitter.com/gpercenter1

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives